In [119]:
%load_ext autoreload
%autoreload 2
%matplotlib inline
import vibrationtesting as vt
from vibrationtesting import sos_modal
import matplotlib.pyplot as plt
import scipy
import numpy as np
import scipy.io as sio
import array_to_latex as a2t
np.set_printoptions(precision = 9, linewidth = 220, suppress = True)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [120]:
a = np.array((1,2,3))
b = np.array((2,3,4))
c=np.column_stack((a,b))
c.shape

(3, 2)

Convert complex modes to real modes

In [203]:
mat_contents=sio.loadmat('1stNaturalFreq.mat')
U1 = mat_contents['U1']
#U1 = vt.real_modes(U1, autorotate = True)
mat_contents=sio.loadmat('2ndNaturalFreq.mat')
U2 = mat_contents['U2']
#U2 = vt.real_modes(U2, autorotate = True)
mat_contents=sio.loadmat('3rdNaturalFreq.mat')
U3 = mat_contents['U3']
#U3 = vt.real_modes(U3, autorotate = True)
mat_contents=sio.loadmat('4rthNaturalFreq.mat')
U4 = mat_contents['U4']
#U4 = vt.real_modes(U4, autorotate = True)
mat_contents=sio.loadmat('5thNaturalFreq.mat')
U5 = mat_contents['U5']
#U5 = vt.real_modes(U5, autorotate = True)
mat_contents=sio.loadmat('6thNaturalFreq.mat')
U6 = mat_contents['U6']
#U6 = vt.real_modes(U6, autorotate = True)

Psi_1 = np.array(U1)
Psi_2 = np.array(U2)
Psi_3 = np.array(U3)
Psi_4 = np.array(U4)
Psi_5 = np.array(U5)
Psi_6 = np.array(U6)
Psi_1=np.column_stack((Psi_1,Psi_2,Psi_3,Psi_4,Psi_5,Psi_6))


Psi_abs = np.abs(Psi_1)*np.real(np.sign(Psi_1))
Psi_1 = Psi_abs
Psi_1



array([[   5.241707706,  -27.127615081,   52.843453543,  107.210143005,   71.139095015, -269.817342785],
       [   4.687209363,  -26.945738191,   52.183186313,   -7.83341953 ,   71.411534453,  -40.625538373],
       [   4.368421773,  -25.121917234,   51.597488464,  -99.159212806,   69.26683148 ,  238.962801192],
       [   3.519108382,   -7.307635452,  -36.871073212,  112.432870575,  -75.970925544, -209.599864678],
       [   3.99369394 ,   -8.550399951,  -37.014491536,   34.494279202,  -65.780768515,  -57.021770026],
       [   4.110844861,   -7.792721262,  -38.903453864,  -97.14023879 ,  -68.483622372,  185.356134448],
       [   3.912418166,   17.983583519,  -33.877855743,  101.225337752,   30.716200755,   95.968190423],
       [   3.359713741,   17.158904587,  -35.675183371,   37.881749912,   46.813407339,  -11.419977031],
       [   3.303682334,   17.92248139 ,  -34.000342956,  -88.24444254 ,   41.527236694, -103.954353298],
       [   2.277194422,   17.704562416,   27.531465665,

In [207]:
mat_contents=sio.loadmat('WingBeamforMAC.mat')
fms = mat_contents['fms']
fms=np.array(fms)
Psi_21 = np.array([fms[2,0], fms[8,0], fms[14,0], fms[20,0], fms[26,0], fms[32,0], fms[38,0], fms[44,0], fms[50,0], fms[56,0], fms[62,0], fms[68,0], fms[74,0], fms[80,0], fms[86,0], fms[92,0], fms[98,0], fms[104,0]])
#0.9044, 0.9044, 0.9044, 0.5459, 0.5459, 0.5459, 0.2593, 0.2593,  0.2593, 0.0696, 0.0696, 0.0696, 0, 0, 0])
#Psi_1 = np.transpose([Psi_1])
#Psi_1 = 
#a=(Psi_1*Psi_2)**2
#a
Psi_22 = np.array([fms[2,1], fms[8,1], fms[14,1], fms[20,1], fms[26,1], fms[32,1], fms[38,1], fms[44,1], fms[50,1], fms[56,1], fms[62,1], fms[68,1], fms[74,1], fms[80,1], fms[86,1], fms[92,1], fms[98,1], fms[104,1]])
Psi_24=np.array([fms[2,4], fms[8,4], fms[14,4], fms[20,4], fms[26,4], fms[32,4], fms[38,4], fms[44,4], fms[50,4], fms[56,4], fms[62,4], fms[68,4], fms[74,4], fms[80,4], fms[86,4], fms[92,4], fms[98,4], fms[104,4]])

Psi_25=np.array([fms[2,5], fms[8,5], fms[14,5], fms[20,5], fms[26,5], fms[32,5], fms[38,5], fms[44,5], fms[50,5], fms[56,5], fms[62,5], fms[68,5], fms[74,5], fms[80,5], fms[86,5], fms[92,5], fms[98,5], fms[104,5]])
Psi_26=np.array([fms[2,6], fms[8,6], fms[14,6], fms[20,6], fms[26,6], fms[32,6], fms[38,6], fms[44,6], fms[50,6], fms[56,6], fms[62,6], fms[68,6], fms[74,6], fms[80,6], fms[86,6], fms[92,6], fms[98,6], fms[104,6]])
Psi_23=np.array([fms[2,3], fms[8,3], fms[14,3], fms[20,3], fms[26,3], fms[32,3], fms[38,3], fms[44,3], fms[50,3], fms[56,3], fms[62,3], fms[68,3], fms[74,3], fms[80,3], fms[86,3], fms[92,3], fms[98,3], fms[104,3]])                
#Psi_2 = np.transpose([Psi_2])
#Psi_2.shape
Psi_2=np.column_stack((Psi_21,Psi_22,Psi_23,Psi_24,Psi_25,Psi_26))
Psi_2

array([[ 1.303055172, -1.511062939,  1.45538456 , -1.507262055, -1.221071448,  1.66978115 ],
       [ 1.303096569, -1.511834301,  1.459195846, -0.         , -1.230962508,  0.         ],
       [ 1.303055172, -1.511062939,  1.45538456 ,  1.507262055, -1.221071448, -1.66978115 ],
       [ 0.904435509, -0.12989042 , -0.666853098, -0.834836394,  0.902775667, -0.188854484],
       [ 0.904496146, -0.130352106, -0.667699499,  0.         ,  0.909819135, -0.         ],
       [ 0.904435509, -0.12989042 , -0.666853098,  0.834836394,  0.902775667,  0.188854484],
       [ 0.545786029,  0.59775021 , -0.375294812,  0.212189574, -0.605038368, -0.927545412],
       [ 0.545857249,  0.597939942, -0.377390031, -0.         , -0.608638479,  0.         ],
       [ 0.545786029,  0.59775021 , -0.375294812, -0.212189574, -0.605038368,  0.927545412],
       [ 0.259255815,  0.601289096,  0.538985585,  0.769605929, -0.040990903,  0.24311203 ],
       [ 0.259330209,  0.602017999,  0.54036016 , -0.         , -0.043

MAC


In [208]:
   
#vt.mac(Psi_true,Psi_real)
nummodes = Psi_1.shape[1]
MAC = np.zeros((nummodes, nummodes))
if Psi_1.shape == Psi_2.shape:
        for i in np.arange(nummodes):
            for j in np.arange(nummodes):
                MAC[i, j] = (abs(np.conj(Psi_1[:, i]) @ Psi_2[:, j])**2 /
                             (np.conj(Psi_1[:, i]) @ Psi_1[:, i] *
                              np.conj(Psi_2[:, j]) @ Psi_2[:, j]))
else:
        print('Mode shape arrays must have the same size.')
    

In [209]:
MAC

array([[ 0.825406385,  0.076783217,  0.121819586,  0.000256617,  0.063672648,  0.000518953],
       [ 0.153799733,  0.874373247,  0.122060215,  0.00024628 ,  0.093517147,  0.000250251],
       [ 0.028431752,  0.210252628,  0.865235993,  0.000109965,  0.149111486,  0.000014794],
       [ 0.008972298,  0.00254086 ,  0.001026265,  0.101801144,  0.000674506,  0.086050501],
       [ 0.067971096,  0.06431233 ,  0.329386648,  0.000037636,  0.816052453,  0.000317923],
       [ 0.006736104,  0.008714956,  0.000320209,  0.86438182 ,  0.001065246,  0.120045373]])

Extension of modes from Modal Analysis to All DOF of a Finite Element Model

In [ ]:
mat_contents=sio.loadmat('WingBeamforMAC.mat')
K = mat_contents['K']
M = mat_contents['M']
measured = np.array([[3,9,15,21,27,33,39,45,51,57,63,69,75,81,87,93,99,105]])
omega=13.54
vt.mode_expansion_from_model(Psi_1, omega, M, K, measured)