In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib inline
import vibrationtesting as vt
import matplotlib.pyplot as plt
import numpy as np
import array_to_latex as a2t
np.set_printoptions(precision = 9, linewidth = 220, suppress = True)

In [2]:
M = np.array([[4, 0, 0],
              [0, 4, 0],
              [0, 0, 4]])
Cso = np.array([[1,0,0],
                [0,0,0],
                [0,0,0]])
K = np.array([[8, -4, 0],
              [-4, 8, -4],
              [0, -4, 4]])
omega, _, Psi_true = vt.sos_modal(M, K)
Bt = np.array([[1],[0],[0]])
Ca = np.array([[1,0,0]])
Cd = Cv = np.zeros_like(Ca)
A, B, C, D = vt.so2ss(M, Cso, K, Bt, Cd, Cv, Ca)
Am, Bm, Cm, Dm, eigenvalues, modes = vt.ss_modal(A, B, C, D)
Psi = vt.real_modes(modes[:,0::2])
Psi_true

array([[-0.163992639,  0.368488115, -0.295504524],
       [-0.295504524,  0.163992639,  0.368488115],
       [-0.368488115, -0.295504524, -0.163992639]])

In [3]:
M = np.array([[4, 0, 0],
              [0, 4, 0],
              [0, 0, 4]])
M

array([[4, 0, 0],
       [0, 4, 0],
       [0, 0, 4]])

In [4]:
 Psi1=np.array([5.2417 + 0.0000j,
   4.6872 - 0.0000j,
   4.3684 + 0.0000j,
   3.5191 + 0.0000j,
   3.9937 - 0.0000j,
   4.1108 + 0.0000j,
   3.9124 + 0.0000j,
   3.3597 + 0.0000j,
   3.3037 - 0.0000j,
   2.2772 - 0.0000j,
   2.1815 + 0.0000j,
   2.0369 - 0.0000j,
   1.5121 + 0.0000j,
   2.0598 - 0.0000j,
   1.7186 - 0.0000j,
  -1.3788 + 0.0000j,
   3.7773 + 0.0000j,
   0.4700 + 0.0000j])
 complex_modes1=np.transpose(Psi1)
Psi2=np.array([-27.1276 + 0.0000j,
 -26.9457 + 0.0000j,
 -25.1219 - 0.0000j,
  -7.3076 + 0.0000j,
  -8.5504 - 0.0000j,
  -7.7927 + 0.0000j,
  17.9836 - 0.0000j,
  17.1589 - 0.0000j,
  17.9225 + 0.0000j,
  17.7046 + 0.0000j,
  17.6982 - 0.0000j,
  17.4871 - 0.0000j,
  12.6957 - 0.0000j,
  12.6223 + 0.0000j,
  12.3028 - 0.0000j,
   4.8623 + 0.0000j,
   7.6143 - 0.0000j,
   4.0450 + 0.0000j])
complex_modes2=np.transpose(Psi2)
complex_modes=np.array([[complex_modes1],
                        [complex_modes2]])
np.size(complex_modes)

36

In [5]:
complex_modes = complex_modes@np.linalg.inv(np.diag(np.diag(complex_modes)))
Psi_est = vt.real_modes(complex_modes)

ValueError: Input must be 1- or 2-d.

In [14]:
    M = np.array([[4, 0, 0],
                  [0, 4, 0],
                  [0, 0, 4]])
    K = np.array([[8, -4, 0],
                  [-4, 8, -4],
                  [0, -4, 4]])
    measured = np.array([[0, 2]])
    omega, zeta, Psi = vt.sos_modal(M, K)
    Psi_measured = np.array([[-0.15], [-0.37]])
    Psi_full = vt.mode_expansion_from_model(Psi_measured, omega[0], M, K, measured)
    print(np.hstack((Psi[:,0].reshape(-1,1), Psi_full)))
    print(omega[0])
    print(Psi_measured)
    print(omega)
    print(Psi)

[[-0.163992639 -0.15       ]
 [-0.295504524  0.288578229]
 [-0.368488115 -0.37       ]]
0.445041867913
[[-0.15]
 [-0.37]]
[ 0.445041868  1.246979604  1.801937736]
[[-0.163992639  0.368488115 -0.295504524]
 [-0.295504524  0.163992639  0.368488115]
 [-0.368488115 -0.295504524 -0.163992639]]
